// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiGb5AvVQI2h_DHNRghROhDy-jbNPOiw4',
    appId: '1:1061397500927:web:88f872973da6d5e0ca4dca',
    messagingSenderId: '1061397500927',
    projectId: 'fluttercontrol',
    authDomain: 'fluttercontrol.firebaseapp.com',
    storageBucket: 'fluttercontrol.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6_zSfBKOwI0tCaHqWcLCLB5S5uYhWDNk',
    appId: '1:1061397500927:android:0d253941976aafb6ca4dca',
    messagingSenderId: '1061397500927',
    projectId: 'fluttercontrol',
    storageBucket: 'fluttercontrol.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDooRIzXVHtixz6VpzEwCojlHX_iZe8b5A',
    appId: '1:1061397500927:ios:2265909ae2c7d12cca4dca',
    messagingSenderId: '1061397500927',
    projectId: 'fluttercontrol',
    storageBucket: 'fluttercontrol.firebasestorage.app',
    iosBundleId: 'com.example.flutterControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDooRIzXVHtixz6VpzEwCojlHX_iZe8b5A',
    appId: '1:1061397500927:ios:2265909ae2c7d12cca4dca',
    messagingSenderId: '1061397500927',
    projectId: 'fluttercontrol',
    storageBucket: 'fluttercontrol.firebasestorage.app',
    iosBundleId: 'com.example.flutterControl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiGb5AvVQI2h_DHNRghROhDy-jbNPOiw4',
    appId: '1:1061397500927:web:5fce49ad9bf6a2c2ca4dca',
    messagingSenderId: '1061397500927',
    projectId: 'fluttercontrol',
    authDomain: 'fluttercontrol.firebaseapp.com',
    storageBucket: 'fluttercontrol.firebasestorage.app',
  );
}
